  
name: Login to OpenShift (OCP)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  ocp-login:
    runs-on: ubuntu-latest

    steps:
      # Checkout (not strictly required for login, but common in workflows)
      - name: Checkout
        uses: actions/checkout@v4

      # Login using the official Red Hat action
      - name: Login to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OCP_SERVER_URL }}
          openshift_token: ${{ secrets.OCP_TOKEN  }}
          
    
